import "./globals.scss";
import type { Metadata } from "next";
import localFont from "next/font/local";
const myFont = localFont({
  src: [
    {
      path: "./styles/HelveticaNowDisplay-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./styles/HelveticaNowDisplay-Bold.woff2",
      weight: "700",
      style: "italic",
    },
  ],
});
// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });

import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "G Revolution - Good Empire",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider publishableKey="pk_test_dmlhYmxlLWdob3VsLTMyLmNsZXJrLmFjY291bnRzLmRldiQ">
      <html lang="en">
        <body className={myFont.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
